[2025-02-07T11:03:12.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T11:03:12.413+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_incremental.transform_and_load scheduled__2025-02-06T00:18:00+00:00 [queued]>
[2025-02-07T11:03:12.437+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_incremental.transform_and_load scheduled__2025-02-06T00:18:00+00:00 [queued]>
[2025-02-07T11:03:12.437+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-07T11:03:12.470+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_and_load> on 2025-02-06 00:18:00+00:00
[2025-02-07T11:03:12.496+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-07T11:03:12.498+0000] {standard_task_runner.py:72} INFO - Started process 61 to run task
[2025-02-07T11:03:12.505+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag_incremental', 'transform_and_load', 'scheduled__2025-02-06T00:18:00+00:00', '--job-id', '570', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpe9cl_0wz']
[2025-02-07T11:03:12.509+0000] {standard_task_runner.py:105} INFO - Job 570: Subtask transform_and_load
[2025-02-07T11:03:12.671+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_incremental.transform_and_load scheduled__2025-02-06T00:18:00+00:00 [running]> on host f34e19f1f8c5
[2025-02-07T11:03:12.930+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag_incremental' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T00:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-06T00:18:00+00:00'
[2025-02-07T11:03:12.935+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-07T11:03:12.936+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-07T11:03:12.936+0000] {logging_mixin.py:190} INFO - Current task name:transform_and_load state:running start_date:2025-02-07 11:03:12.414506+00:00
[2025-02-07T11:03:12.937+0000] {logging_mixin.py:190} INFO - Dag name:etl_dag_incremental and current dag run status:running
[2025-02-07T11:03:12.938+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T11:03:14.162+0000] {etl.py:237} INFO - Unified transactions count: 18240
[2025-02-07T11:03:14.172+0000] {etl.py:242} INFO - Custumers transactions count: 18240
[2025-02-07T11:03:14.174+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.36
[2025-02-07T11:03:14.178+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-07T11:03:14.179+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-07T11:03:17.167+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-07T11:03:44.255+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-07T11:03:44.261+0000] {connection.py:789} INFO - closed
[2025-02-07T11:03:44.363+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-07T11:03:44.482+0000] {etl.py:301} ERROR - Error: list indices must be integers or slices, not str
[2025-02-07T11:03:44.485+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 296, in transform_and_load
    last_timestamp = max([row["created_at"] for row in online_orders_data + physical_data])
                          ~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-02-07T11:03:44.533+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-07T11:03:44.535+0000] {logging_mixin.py:190} INFO - Task start:2025-02-07 11:03:12.414506+00:00 end:2025-02-07 11:03:44.531977+00:00 duration:32.117471
[2025-02-07T11:03:44.538+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_and_load> dag:<DAG: etl_dag_incremental> dagrun:<DagRun etl_dag_incremental @ 2025-02-06 00:18:00+00:00: scheduled__2025-02-06T00:18:00+00:00, state:running, queued_at: 2025-02-07 10:57:11.380167+00:00. externally triggered: False>
[2025-02-07T11:03:44.540+0000] {logging_mixin.py:190} INFO - Failure caused by list indices must be integers or slices, not str
[2025-02-07T11:03:44.542+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_dag_incremental, task_id=transform_and_load, run_id=scheduled__2025-02-06T00:18:00+00:00, execution_date=20250206T001800, start_date=20250207T110312, end_date=20250207T110344
[2025-02-07T11:03:44.621+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T11:03:44.622+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 570 for task transform_and_load (list indices must be integers or slices, not str; 61)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl.py", line 296, in transform_and_load
    last_timestamp = max([row["created_at"] for row in online_orders_data + physical_data])
                          ~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2025-02-07T11:03:44.725+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T11:03:44.799+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T11:03:44.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
